# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tiny-nlp-datablock',
                'doc_host': 'https://numb3r33.github.io',
                'git_url': 'https://github.com/numb3r33/tiny-nlp-datablock',
                'lib_path': 'tiny_nlp_datablock'},
  'syms': {'tiny_nlp_datablock.core': {'tiny_nlp_datablock.core.run_one_batch': ('core.html#run_one_batch', 'tiny_nlp_datablock/core.py')}}}
