"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['run_one_batch']

# %% ../nbs/00_core.ipynb 2
from fastai.text.all import *

# %% ../nbs/00_core.ipynb 8
def run_one_batch():
    path = untar_data(URLs.IMDB_SAMPLE)
    df = pd.read_csv(path/'texts.csv')
    
    imdb_block = DataBlock(
                        blocks=(TextBlock.from_df('text'), CategoryBlock), # Our X is text, our Y is a category
                        get_x=ColReader('text'),
                        get_y=ColReader('label'),                          # The label is in the 'label' column
                        splitter=ColSplitter('is_valid')                   # Use the 'is_valid' column to split train/val
                        )

    dls = imdb_block.dataloaders(df, bs=4) # Small batch size for easy inspection
    dls.show_batch(max_n=2)

run_one_batch()
